name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/foo
      DB_SSL: false
      VITE_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/foo
      VITE_DB_SSL: false
      BREVO_API_KEY: foobar
      VITE_BREVO_API_KEY: foobar
      POLYGON_API_KEY: foobar
      OPENAI_API_KEY: foobar
      UPLOAD_SECRET: foobar

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: List test files
        run: ls -R src/tests

      - name: Run tests
        run: npx cross-env ENVIRONMENT=TEST vitest run src/tests/{api,db,unit}
